fn main() {
  // `open_online_window` is an app-defined command (not a plugin), so its
  // permission identifiers (`allow-open-online-window` / `deny-open-online-window`)
  // are autogenerated here and referenced bare (no plugin prefix) from
  // capabilities/default.json. Only the "main" window's capability grants it;
  // the "online" window itself gets zero IPC surface (see capabilities/online.json).
  tauri_build::try_build(
    tauri_build::Attributes::new()
      .app_manifest(tauri_build::AppManifest::new().commands(&["open_online_window"])),
  )
  .expect("failed to run tauri-build");
}
