fn main() {
  // These are app-defined commands (not plugin commands), so their permission
  // identifiers are autogenerated here and referenced bare from
  // capabilities/default.json. Only the "main" window may invoke them; the
  // "online" window itself gets zero IPC surface (see capabilities/online.json).
  tauri_build::try_build(
    tauri_build::Attributes::new()
      .app_manifest(tauri_build::AppManifest::new().commands(&[
        "open_online_window",
        "open_help_destination",
      ])),
  )
  .expect("failed to run tauri-build");
}
