fn main() {
  // App-defined commands (not plugin commands): their permission identifiers
  // are autogenerated here and referenced bare from capabilities/default.json.
  // Only the "main" (launcher) window may invoke them. The "online" and
  // "game" windows get zero IPC surface; see capabilities/online.json and
  // capabilities/game.json.
  tauri_build::try_build(
    tauri_build::Attributes::new().app_manifest(tauri_build::AppManifest::new().commands(&[
      "open_online_window",
      "open_help_destination",
      "open_game_window",
      "game_start",
      "game_stop",
      "game_status",
      "game_request",
      "list_worlds",
      "create_world",
      "touch_world",
      "delete_world",
    ])),
  )
  .expect("failed to run tauri-build");
}
